import type { LocalAgentReport } from "../../src/types/index.ts"

export const sampleLocalReport: LocalAgentReport = {
  reportType: "local-agent-context-audit",
  generatedAt: "2026-07-01T12:00:00Z",
  window: "7d",
  summary: {
    cacheLeakScore: 52,
    recoverableCashSaving: null,
    estimatedCacheMissRange: { lowPercent: 12, highPercent: 18 },
    agentsScanned: 3,
    sessionsFound: 342,
    sessionsInWindow: 89,
    sessionsAnalyzed: 89,
    totalTokens: 2_840_000,
    inputTokens: 2_120_000,
    outputTokens: 720_000,
    cacheReadTokens: 186_000,
    cacheWriteTokens: 412_000,
    cacheReadPercent: 0.088,
    modelCostUsd: 12.4,
    tokenAccounting: "mixed",
    visibility: "exact_cache_telemetry",
    toolCalls: 1_247,
    subagentRuns: 38,
    modelsDetected: 4,
    confidence: "medium",
    mainFinding:
      "Dynamic context (git diffs, terminal output, timestamps) appears before stable repo rules in 68% of analyzed sessions, reducing prefix reuse across Claude Code and OpenCode.",
  },
  agents: [
    {
      provider: "claude-code",
      detected: true,
      sessionsFound: 156,
      sessionsInWindow: 42,
      sessionsAnalyzed: 42,
      totalTokens: 1_420_000,
      inputTokens: 1_060_000,
      outputTokens: 360_000,
      cacheReadTokens: 124_000,
      cacheWriteTokens: 198_000,
      cacheReadPercent: 0.117,
      modelCostUsd: 6.8,
      tokenAccounting: "observed",
      visibility: "exact_cache_telemetry",
      telemetrySources: ["otel_logs"],
      telemetryConfidence: "high",
      confidenceNotes: ["Sample Claude Code OTel fields include input_tokens, output_tokens, cache_read_tokens, and cache_creation_tokens."],
      toolCalls: 624,
      subagentRuns: 18,
      topSubagents: [
        { name: "explore", sessions: 12 },
        { name: "general", sessions: 6 },
      ],
      modelsDetected: ["claude-sonnet-4-20250514", "claude-haiku-3.5"],
      cacheLeakScore: 48,
      estimatedCacheMissRange: { lowPercent: 14, highPercent: 22 },
      recoverableCashSaving: null,
      mainFinding:
        "Git diffs and terminal output load before AGENTS.md rules in 71% of sessions, breaking prefix stability.",
      findings: [
        {
          id: "dynamic-context-early",
          title: "Dynamic context loads first",
          severity: "high",
          evidence: "git diff output and terminal logs appear before repo rules in 30 of 42 sessions",
          recommendation: "Move AGENTS.md and CLAUDE.md to the top of the context window, push diffs and logs to the tail.",
          agent: "claude-code",
        },
        {
          id: "weak-agents-md",
          title: "AGENTS.md missing or minimal",
          severity: "medium",
          evidence: "AGENTS.md exists but contains only 12 lines of stable rules; 42 sessions repeat boilerplate in ad-hoc prompts",
          recommendation: "Expand AGENTS.md with repo layout, commands, architecture boundaries, and test expectations.",
          agent: "claude-code",
        },
      ],
      recommendations: [
        {
          id: "claude-stable-first",
          title: "Put stable instructions first",
          action: "Put AGENTS.md/CLAUDE.md first in every session context.",
        },
        {
          id: "claude-dynamic-tail",
          title: "Move dynamic content to tail",
          action: "Move git diffs, terminal output, and stack traces to the dynamic tail.",
        },
        {
          id: "claude-summarize",
          title: "Summarize instead of replay",
          action: "Summarize previous sessions instead of replaying full transcripts.",
        },
      ],
    },
    {
      provider: "opencode",
      detected: true,
      sessionsFound: 128,
      sessionsInWindow: 38,
      sessionsAnalyzed: 38,
      totalTokens: 980_000,
      inputTokens: 740_000,
      outputTokens: 240_000,
      cacheReadTokens: 62_000,
      cacheWriteTokens: 168_000,
      cacheReadPercent: 0.063,
      modelCostUsd: 4.1,
      tokenAccounting: "observed",
      visibility: "exact_cache_telemetry",
      telemetrySources: ["local_db"],
      telemetryConfidence: "high",
      confidenceNotes: ["Sample OpenCode local database fields include tokens_input, tokens_output, tokens_cache_read, and tokens_cache_write."],
      toolCalls: 486,
      subagentRuns: 14,
      topSubagents: [
        { name: "explore", sessions: 8 },
        { name: "writer", sessions: 6 },
      ],
      modelsDetected: ["gpt-4.1", "gpt-4.1-mini"],
      cacheLeakScore: 58,
      estimatedCacheMissRange: { lowPercent: 10, highPercent: 16 },
      recoverableCashSaving: null,
      mainFinding:
        "Timestamps and session metadata inject before stable project instructions, reducing prefix reuse.",
      findings: [
        {
          id: "dynamic-context-early",
          title: "Timestamps and metadata before rules",
          severity: "high",
          evidence: "Timestamps, session IDs, and branch state appear before project rules in 26 of 38 sessions",
          recommendation: "Inject stable project context first, then append dynamic metadata.",
          agent: "opencode",
        },
        {
          id: "repeated-project-context",
          title: "Repeated project boilerplate",
          severity: "medium",
          evidence: "Repo layout and command hints repeated in 19 of 38 sessions instead of using a shared instruction file",
          recommendation: "Create a shared AGENTS.md and reference it instead of repeating boilerplate.",
          agent: "opencode",
        },
      ],
      recommendations: [
        {
          id: "opencode-agents-md",
          title: "Create AGENTS.md",
          action: "Create AGENTS.md with stable project rules.",
        },
        {
          id: "opencode-load-order",
          title: "Load context in correct order",
          action: "Load project context before session-specific metadata.",
        },
        {
          id: "opencode-no-repeat",
          title: "Remove repeated boilerplate",
          action: "Remove repeated boilerplate from individual prompts.",
        },
      ],
    },
    {
      provider: "codex",
      detected: true,
      sessionsFound: 58,
      sessionsInWindow: 9,
      sessionsAnalyzed: 9,
      totalTokens: 440_000,
      inputTokens: 320_000,
      outputTokens: 120_000,
      cacheReadTokens: 0,
      cacheWriteTokens: 46_000,
      cacheReadPercent: null,
      modelCostUsd: 1.5,
      tokenAccounting: "estimated",
      visibility: "transcript_context_only",
      telemetrySources: ["transcript"],
      telemetryConfidence: "low",
      confidenceNotes: ["Sample Codex record is transcript-only; cache telemetry is not reported."],
      toolCalls: 137,
      subagentRuns: 6,
      topSubagents: [{ name: "general", sessions: 4 }],
      modelsDetected: ["codex-mini-latest"],
      cacheLeakScore: 64,
      mainFinding: "Cache telemetry not exposed in local Codex session files; hygiene score based on transcript analysis.",
      findings: [
        {
          id: "local-cache-telemetry-not-reported",
          title: "Cache telemetry unavailable",
          severity: "low",
          evidence: "Codex local sessions do not expose cache-read/cache-write token fields",
          recommendation: "Use transcript-based hygiene findings as the reliable signal for Codex sessions.",
          agent: "codex",
        },
      ],
      recommendations: [
        {
          id: "codex-hygiene-focus",
          title: "Focus on transcript hygiene",
          action: "Focus on context hygiene findings from transcript analysis.",
        },
        {
          id: "codex-cache-unknown",
          title: "Treat cache as unknown",
          action: "Cache telemetry is not available; treat cache-read as unknown.",
        },
      ],
    },
  ],
  modelsDetected: [
    { rawName: "claude-sonnet-4-20250514", sessions: 32, pricingKnown: true, pricingConfidence: "high" },
    { rawName: "claude-haiku-3.5", sessions: 10, pricingKnown: true, pricingConfidence: "high" },
    { rawName: "gpt-4.1", sessions: 24, pricingKnown: true, pricingConfidence: "high" },
    { rawName: "gpt-4.1-mini", sessions: 14, pricingKnown: true, pricingConfidence: "high" },
    { rawName: "codex-mini-latest", sessions: 9, pricingKnown: false, pricingConfidence: "low" },
  ],
  projects: [
    {
      path: "~/code/support-copilot",
      sessions: 38,
      totalTokens: 1_180_000,
      cacheReadPercent: 0.092,
      modelCostUsd: 5.2,
      hasAgentsMd: true,
      hasClaudeMd: true,
      advice: ["Keep AGENTS.md stable", "Move logs to tail"],
    },
    {
      path: "~/code/docs-rag",
      sessions: 28,
      totalTokens: 820_000,
      cacheReadPercent: 0.074,
      modelCostUsd: 3.8,
      hasAgentsMd: false,
      hasClaudeMd: false,
      advice: ["Add AGENTS.md with repo rules", "Add CLAUDE.md for Claude Code"],
    },
    {
      path: "~/code/refund-service",
      sessions: 23,
      totalTokens: 840_000,
      cacheReadPercent: null,
      modelCostUsd: 3.4,
      hasAgentsMd: true,
      hasClaudeMd: false,
      advice: ["Add CLAUDE.md if using Claude Code", "Move dynamic state to tail"],
    },
  ],
  activity: {
    toolCalls: 1_247,
    subagentRuns: 38,
    topSubagents: [
      { name: "explore", sessions: 20 },
      { name: "general", sessions: 10 },
      { name: "writer", sessions: 6 },
      { name: "editor", sessions: 2 },
    ],
  },
  findings: [
    {
      id: "dynamic-context-early",
      title: "Dynamic context loads before stable rules",
      severity: "high",
      evidence: "git diffs, terminal output, and timestamps appear before repo instructions in 68% of sessions",
      recommendation: "Put AGENTS.md/CLAUDE.md first, push diffs and logs to the tail.",
    },
    {
      id: "weak-agents-md",
      title: "AGENTS.md missing or minimal in key projects",
      severity: "medium",
      evidence: "docs-rag has no AGENTS.md; refund-service has no CLAUDE.md",
      recommendation: "Add stable repo rules to both projects.",
    },
    {
      id: "repeated-project-context",
      title: "Repeated boilerplate across sessions",
      severity: "medium",
      evidence: "Repo layout and command hints repeated in 19 of 89 sessions",
      recommendation: "Use a shared instruction file instead of repeating boilerplate.",
    },
    {
      id: "local-cache-telemetry-not-reported",
      title: "Cache telemetry unavailable for Codex",
      severity: "low",
      evidence: "Codex local sessions do not expose cache-read/cache-write token fields",
      recommendation: "Use transcript-based hygiene findings as the reliable signal.",
    },
  ],
  recommendations: [
    {
      id: "stable-first",
      title: "Put stable instructions first",
      action: "Put stable project instructions first in every session context.",
    },
    {
      id: "dynamic-tail",
      title: "Move dynamic content to tail",
      action: "Move diffs, logs, timestamps, and tool output to the dynamic tail.",
    },
    {
      id: "add-agents-md",
      title: "Add or expand instruction files",
      action: "Add or expand AGENTS.md in docs-rag and CLAUDE.md in refund-service.",
    },
    {
      id: "summarize-sessions",
      title: "Summarize instead of replay",
      action: "Summarize previous sessions instead of replaying full transcripts.",
    },
  ],
  diagnostics: {
    providers: [
      {
        provider: "claude-code",
        rootPaths: ["~/.claude/projects"],
        candidatesFound: 156,
        candidatesInWindow: 42,
        filesAttempted: 156,
        parsedSessions: 42,
        skippedFiles: 0,
        failedFiles: 0,
        topFailureReasons: [],
        sampleCandidates: [],
      },
      {
        provider: "opencode",
        rootPaths: ["~/.opencode/sessions"],
        candidatesFound: 128,
        candidatesInWindow: 38,
        filesAttempted: 128,
        parsedSessions: 38,
        skippedFiles: 0,
        failedFiles: 0,
        topFailureReasons: [],
        sampleCandidates: [],
      },
      {
        provider: "codex",
        rootPaths: ["~/.codex/sessions"],
        candidatesFound: 58,
        candidatesInWindow: 9,
        filesAttempted: 58,
        parsedSessions: 9,
        skippedFiles: 0,
        failedFiles: 0,
        topFailureReasons: [],
        sampleCandidates: [],
      },
    ],
  },
  pricingDisclaimer:
    "Dollar values are model-cost equivalents only. Subscriptions, promotions, and enterprise pricing are not visible. Cache-discount ranges are conservative where exact cached-input pricing was unavailable.",
}
